using Grpc.Core;
using TestGrpc;

namespace GrpcServer
{
    // TestGrpcService is autogenerated by Grpc.Tools
    public class GrpcServerService : TestGrpcService.TestGrpcServiceBase
    {
        public override async Task<GetResponse> Get(GetRequest request, ServerCallContext context)
        {
            return await Task.FromResult(new GetResponse() { Item = new GetItemModel { Id = request.Id, Name = "TestItem" } });
        }
    }
}
