using TestGrpc;
using static TestGrpc.TestGrpcService;

namespace GrpcClient
{
    // TestGrpcServiceClient is autogenerated by Grpc.Tools
    public class GrpcClientService(TestGrpcServiceClient client) : IGrpcClientService
    {
        private readonly TestGrpcServiceClient _client = client;

        public async Task<GetResponse> Get(string id)
        {
            return await _client.GetAsync(new GetRequest() { Id = id });
        }
    }
}
