worker_processes 1;

events {
    worker_connections 1024;
}

http {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    server {
        listen 80;

        location / {
            root /usr/share/nginx/html;
            index gateway-index.html;
        }

        location /custom-gateway/text/ {
            proxy_pass http://text-api:8080/;
        }

        location /custom-gateway/numbers/ {
            proxy_pass http://numbers-api:8080/;
        }
    }
}
